version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mah3uz-gopeed_web_1
      APP_PORT: 9999
  gopeed:
    image: liwei2633/gopeed:v1.8.3@sha256:b28c797b6408d53d7803ccbc32649fc4ca8567c0d994a82bf8dfdf87f0765feb
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - ${APP_DATA_DIR}/data/storage:/app/storage
      - ${UMBREL_ROOT}/data/storage/downloads:/app/Downloads